server:
  port: 8088

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      port: 6379
      host: 172.17.0.3
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

docker:
  email: hwryu990927@gmail.com
  password: hwryu990927!
  username: uhanuu
  host: tcp://172.17.0.2:2376


compile:
  path: /Users/ryu/goorm/ide/webide/compile/


kakao:
  client_id: 66bebbcee6a6edfb974809d9fd180e94
  redirect_uri: http://localhost:8080/ide/login/kakao

application:
  security:
    jwt:
      secret-key: secretKeysldkfjlaijl1kjf1255dslkfjlefldkjfladisjflkdajflqijfdlkjalfijawlkdfjlkjafldijflakdjflaidjflkadjflakdjfladksjflidjaf
      expiration: 30
      refresh-token:
        expiration: 60
